# Generated by Django 6.0.3 on 2026-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_numero', models.IntegerField()),
                ('endereco_cidade', models.CharField(max_length=40)),
                ('endereco_estado', models.CharField(max_length=2)),
                ('tipo_imovel', models.CharField(max_length=20)),
                ('consumo_energia', models.IntegerField(blank=True, null=True)),
                ('imagem', models.FileField(blank=True, default=None, null=True, upload_to='images/orcamento')),
            ],
        ),
    ]
