# Generated by Django 6.0.3 on 2026-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_orcamento',
            name='nome_cliente',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
