# Generated by Django 6.0.3 on 2026-04-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dados_orcamento_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_orcamento',
            name='data_inicial_orcamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
