# Generated by Django 6.0.3 on 2026-04-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dados_orcamento_data_inicial_orcamento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dados_orcamento',
            table='orcamento',
        ),
    ]
