# Generated by Django 6.0.3 on 2026-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dados_orcamento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_orcamento',
            name='status',
            field=models.CharField(default='aguardando', max_length=30),
        ),
    ]
