# Generated by Django 6.0.3 on 2026-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dados_orcamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_orcamento',
            name='data_inicial_orcamento',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do orçamento'),
        ),
        migrations.AlterField(
            model_name='dados_orcamento',
            name='endereco_cidade',
            field=models.CharField(max_length=40, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='dados_orcamento',
            name='endereco_estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dados_orcamento',
            name='endereco_logradouro',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='dados_orcamento',
            name='endereco_numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='dados_orcamento',
            name='nome_cliente',
            field=models.CharField(max_length=100, verbose_name='Nome do cliente'),
        ),
    ]
